# Generated by Django 4.1.3 on 2022-12-01 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("log", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(model_name="speak", name="user",),
        migrations.AddField(
            model_name="speak",
            name="username",
            field=models.CharField(default="", max_length=30),
        ),
    ]
